<x-layout>

    <div class="price_banner">
        <div class="container grid">
            <div id="ga_section_title">
                <h2>Market EWT/USD:</h2>
            </div>
            <div id="ga_last_price">
                <div class="pb_title">Last Price</div>
                <div class="pb_value">&dollar; {{number_format($market->price,2)}}</div>
            </div>
            <div id="ga_24h_pchange">
                <div class="pb_title">24H Price change</div>
                <div class="pb_value">{{number_format($market->percent_change_24h,2)}}%</div>
            </div>
            <div id="ga_24h_volume">
                <div class="pb_title">24H Volume</div>
                <div class="pb_value">&dollar; {{number_format($market->volume_24h,2)}}</div>
            </div>
            <div id="ga_24h_vchange">
                <div class="pb_title">24H Volume change</div>
                <div class="pb_value">{{number_format($market->volume_change_24h,2)}}%</div>
            </div>
            <div id="ga_market_cap">
                <div class="pb_title">Market Cap</div>
                <div class="pb_value">&dollar; {{number_format($data['circulating-supply']*$market->price)}}</div>
            </div>
            <div id="ga_fd_market_cap">
                <div class="pb_title">Fully Diluted Market Cap</div>
                <div class="pb_value">&dollar; {{number_format($market->fully_diluted_market_cap)}}</div>
            </div>
        </div>
    </div>

    <div class="container grid metrics">

        <div id="ga_supply" class="block">
            <h2>Supply (EWT)</h2>
            <table>
                <tr>
                    <td class="row-title">Max Supply <i class="fa fa-light fa-circle-info" title="The maximum amount of EWT that will be brought into existence. It is generated by block rewards that are added to the Validator wallets and EWF Community Fund wallet."></i></td>
                    <td class="monospace">{{number_format(100000000)}}</td>
                </tr>
                <tr>
                    <td class="row-title">Total Supply <i class="fa fa-light fa-circle-info" title="The total supply of EWT is fetched from https://explorer.energyweb.org/api?module=stats&action=coinsupply"></td>
                    <td class="monospace">{{number_format($data['total'])}}</td>
                </tr>

                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>

                <tr>
                    <td colspan="2" class="row-title">Not in circulation  <i class="fa fa-light fa-circle-info" title="This is considered not in circulation. Given that supply.energyweb.org gives a circulating supply which is the same as the total minus these wallets."></td>
                </tr>
                <tr>
                    <td class="row-subtitle">Team (Endowment & Ops):</td>
                    <td class="monospace">{{number_format($wallets['team']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-subtitle">Community Fund:</td>
                    <td class="monospace">{{number_format($wallets['community']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-subtitle">Distribution Contract<b>*</b>:</td>
                    <td class="monospace">{{number_format($wallets['holding']['balance'])}}</td>
                </tr>

                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>

                <tr>
                    <td colspan="2" class="row-title">In Circulation  <i class="fa fa-light fa-circle-info" title="All other wallets that are considered in circulation. Lockup periods have ended, so these funds can move into general circulation at any moment."></td>
                </tr>
                <tr>
                    <td class="row-subtitle">Founder 2:</td>
                    <td class="monospace">{{number_format($data['founder2-total'])}}</td>
                </tr>
                <tr>
                    <td class="row-subtitle">Round A Affiliates:</td>
                    <td class="monospace">{{number_format($data['rounda-total'])}}</td>
                </tr>
                <tr>
                    <td class="row-subtitle">Round B/C Affiliates:</td>
                    <td class="monospace">{{number_format($data['roundbc-total'])}}</td>
                </tr>
                <tr>
                    <td class="row-subtitle">All other:</td>
                    <td class="monospace">{{number_format($data['circulating-supply']-$data['founder2-total']-$data['rounda-total']-$data['roundbc-total'])}}</td>
                </tr>

                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>

                <tr>
                    <td class="row-title">Circulating Supply <i class="fa fa-light fa-circle-info" title="The total circulating supply of EWT is fetched from https://supply.energyweb.org and is confirmed by EW to be correct. It seems to be the tot supply minus the Team, Community Fund and Distribution Contract wallets."></td>
                    <td class="monospace">{{number_format($data['circulating-supply'])}}</td>
                </tr>
                <tr>
                    <td colspan="2">Circulating = Total - Team - Community - Distribution</td>
                </tr>
            </table>

            <p><b>*</b> The distribution contract still holds the 5m EWT allocated to Founder 1</p>
        </div>

        <div id="ga_exchanges" class="block">
            <h2>Exchanges</h2>
            <table>
                <tr>
                    <td class="row-title">Kucoin</td>
                    <td class="monospace"></td>
                </tr>
                <tr>
                    <td class="row-subtitle">Cold Wallet:</td>
                    <td class="monospace">{{number_format($wallets['kucoin-cold']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-subtitle">Hot Wallet #1:</td>
                    <td class="monospace">{{number_format($wallets['kucoin-hot']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-subtitle">Hot Wallet #2:</td>
                    <td class="monospace">{{number_format($wallets['kucoin-hot2']['balance'])}}</td>
                </tr>

                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>

                <tr>
                    <td class="row-title">Kraken:</td>
                    <td class="monospace">{{number_format($wallets['kraken']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">Bitmart:</td>
                    <td class="monospace">{{number_format($wallets['bitmart']['balance']+$wallets['bitmart2']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">Gate.io:</td>
                    <td class="monospace">{{number_format($wallets['gate']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">Hotbit:</td>
                    <td class="monospace">{{number_format($wallets['hotbit']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">Liquid:</td>
                    <td class="monospace">{{number_format($wallets['liquid']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">Bitrue:</td>
                    <td class="monospace">{{number_format($wallets['bitrue']['balance'])}}</td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="row-title">Total Exchanges:</td>
                    <td class="monospace">{{number_format($data['total-exchanges'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">Exchanges %:</td>
                    <td class="monospace">{{number_format($data['total-exchanges']/$data['circulating-supply']*100,2)}}%</td>
                </tr>
            </table>
        </div>

        <div id="ga_staking" class="block">
            <h2>Staking Pools</h2>
            <table>
                <tr>
                    <td class="row-title">🔴 Booster Pool:</td>
                    <td class="monospace">{{number_format($wallets['booster']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">🔵 EEA Pool:</td>
                    <td class="monospace">{{number_format($wallets['eea']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">🟣 CRC Pool:</td>
                    <td class="monospace">{{number_format($wallets['crc']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">🟢 Green Pool:</td>
                    <td class="monospace">{{number_format($wallets['greenpool']['balance'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">⚪️ Silver Pool:</td>
                    <td class="monospace">🔜 22/12/22</td>
                </tr>
                <tr>
                    <td class="row-title">🟠 Gold Pool:</td>
                    <td class="monospace">🔜 22/12/22</td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="row-title">Total in staking pools:</td>
                    <td class="monospace">{{number_format($data['total-staked'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">% of circulating supply:</td>
                    <td class="monospace">{{number_format($data['total-staked']/$data['circulating-supply']*100,2)}}%</td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>
            </table>
        </div>

        <div id="ga_validators" class="block">
            <h2>Validators</h2>
            <table>
                <tr>
                    <td>&nbsp;</td>
                    <td class="column-title right">Validators</td>
                    <td class="column-title right">Mining wallets</td>
                    <td class="column-title right">Holding EWT</td>
                </tr>
                <tr>
                    <td class="row-title">Active</td>
                    <td class="monospace">{{number_format($data['active-validators-count'])}}</td>
                    <td class="monospace">{{number_format($data['active-miners-count'])}}</td>
                    <td class="monospace">{{number_format($data['active-miners-holding'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">Inactive</td>
                    <td class="monospace">{{number_format($data['inactive-validators-count'])}}</td>
                    <td class="monospace">{{number_format($data['inactive-miners-count'])}}</td>
                    <td class="monospace">{{number_format($data['inactive-miners-holding'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">Unknown</td>
                    <td class="monospace"></td>
                    <td class="monospace">{{number_format($data['unknown-miners-count'])}}</td>
                    <td class="monospace">{{number_format($data['unknown-miners-holding'])}}</td>
                </tr>
            </table>
            <p>See: <a href="https://validator-dashboard.sandbox.energyweb.org/index.html" target="_blank">Official Energy Web Validator Dashboard</a> <i class="fa fa-external-link"></i></p>
        </div>

        <div id="ga_bridged" class="block">
            <h2>Bridged (EWTB)</h2>
            <table>
                <tr>
                    <td class="row-title">Minted:</td>
                    <td class="monospace">{{number_format($data['ewtb-total'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">TXs Last Day:</td>
                    <td class="monospace">{{number_format($data['ewtb-last-day'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">TXs Last Week:</td>
                    <td class="monospace">{{number_format($data['ewtb-last-week'])}}</td>
                </tr>
                <tr>
                    <td class="row-title">TXs Last Month:</td>
                    <td class="monospace">{{number_format($data['ewtb-last-month'])}}</td>
                </tr>
            </table>
        </div>

    </div>



    <div class="container grid grid-dashboard">

        <div class="distribution-container">
            <div class="block">
                <h2>Token distribution</h2>
                <table class="show-table">
                    <thead>
                        <tr>
                            <th>Category</th>
                            <th>Description</th>
                            <th>Token Allocation <i class="fa fa-normal fa-circle-info" title="This is the amount of EWT that was given by the holding contract. See: https://explorer.energyweb.org/address/0x1204700000000000000000000000000000000004/contracts#address-tabs"></i></th>
                            <th>Lockup Period <i class="fa fa-normal fa-circle-info" title="All tokens have been released. There are no more tokens locked up."></i></th>
                            <th>Current Balance  <i class="fa fa-normal fa-circle-info" title="The current balance of the wallet that received the Token Allocation OR the sum of wallets it is distributed to. E.g. in case of RMI"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>EWF Operating Fund</td>
                            <td>Tokens for EWF operations</td>
                            <td class="monospace">10,901,792</td>
                            <td>n/a</td>
                            <td rowspan="2" class="monospace">{{number_format($wallets['team']['balance'])}}</td>
                        </tr>
                        <tr>
                            <td>EWF Endowment</td>
                            <td>Tokens intended for additional technology development in support of EWF mission</td>
                            <td class="monospace">10,000,000</td>
                            <td>3 months</td>
                        </tr>
                        <tr>
                            <td>EWF Community Fund</td>
                            <td>Community fund tokens will be used to support development of new technologies in the EWF ecosystem. Released linearly over 10 years</td>
                            <td class="monospace">37,900,000</td>
                            <td>n/a</td>
                            <td class="monospace">{{number_format($wallets['community']['balance'])}}</td>
                        </tr>
                        <tr>
                            <td>Validator Block Reward</td>
                            <td>Allocated to block validation rewards, and released continuously (on a per-block basis) over a period of 10 years in a logarithmic curve</td>
                            <td class="monospace">10,000,000</td>
                            <td>n/a</td>
                            <td class="monospace">{{number_format($data['active-miners-holding'])}}</td>
                        </tr>
                        <tr>
                            <td rowspan="2">Founder Tokens</td>
                            <td rowspan="2">Allocated to EWF co-founders Rocky Mountain Institute and Grid Singularity</td>
                            <td rowspan="2" class="monospace">10,000,000</td>
                            <td rowspan="2">24 months</td>
                            <td class="monospace">{{number_format($wallets['holding']['balance'])}}</td>
                        </tr>
                        <tr>
                            <td class="monospace">{{number_format($data['founder2-total'])}}</td>
                        </tr>
                        <tr>
                            <td>Round A Affiliates</td>
                            <td>Allocated to the 10 initial Affiliates of EWF</td>
                            <td class="monospace">5,000,000</td>
                            <td>3 months</td>
                            <td class="monospace">{{number_format($data['rounda-total'])}}</td>
                        </tr>
                        <tr>
                            <td>Round B Affiliates</td>
                            <td>Allocated to Affiliates who joined EWF in a B round of fundraising</td>
                            <td class="monospace">15,863,208</td>
                            <td>6 months</td>
                            <td rowspan="2" class="monospace">{{number_format($data['roundbc-total'])}}</td>
                        </tr>
                        <tr>
                            <td>Round C Affiliates</td>
                            <td>Allocated to Affiliates who joined EWF</td>
                            <td class="monospace">335,000</td>
                            <td>6 months</td>
                        </tr>
                        <tr>
                            <th colspan="2" class="text-right">Total</th>
                            <th class="monospace text-right">100,000,000</th>
                            <th></th>
                            <th class="text-right">
                                <span class="monospace">{{number_format($wallets['team']['balance']+$wallets['community']['balance']+$data['active-miners-holding']+$wallets['holding']['balance']+$data['founder2-total']+$data['rounda-total']+$data['roundbc-total'])}}</span><br />
                                <span class="note">{{number_format(($wallets['team']['balance']+$wallets['community']['balance']+$data['active-miners-holding']+$wallets['holding']['balance']+$data['founder2-total']+$data['rounda-total']+$data['roundbc-total'])/$data['total']*100)}}% of Total Supply</span>
                            </th>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</x-layout>
