<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Validator extends Model
{
    use HasFactory;

    public function wallets() {
        return $this->hasMany(Wallet::class);
    }


    public function seed() {

        // clear the database before seeding
        $this->truncate();

        $validators = [
            ["1","3Degrees","USA","2018","https://3degreesinc.com/","For over 15 years, our renewable energy, transportation decarbonization, and sustainability solutions have made it possible for businesses and utilities to answer the call for immediate and meaningful climate action."],
            ["1","Acciona","Spain","2018","https://www.acciona.com/","ACCIONA is leading the corporate fight to mitigate the effects of the climate emergency and accelerate change towards a decarbonised energy model. A trailblazer in the initial phases of the renewable sector, the company is the largest 100 % clean energy company in the world. It is currently the leader in the development, engineering, construction, operation and maintenance of renewable assets, supported by a stable growth model and guaranteed with more than 1.000 GW of capacity under construction. It leads the global ranking of Energy Intelligence's Top 100 Green Utilities for the fifth consecutive year as the world's largest 100 % renewable energy corporation and has avoided the emission into the atmosphere of nearly 15 million tons of CO₂ in 2019 (equivalent to 1.2 million households), equal to approximately twice the total annual emissions in the city of Madrid."],
            ["1","AES","USA","2018","http://aes.com/","The AES Corporation (NYSE: AES) is a Fortune 500 global power company. We provide affordable, sustainable energy to 14 countries through our diverse portfolio of distribution businesses as well as thermal and renewable generation facilities. Our workforce is committed to operational excellence and meeting the world’s changing power needs. Our 2019 revenues were $10 billion and we own and manage $34 billion in total assets. AES pursues advances in the energy sector through internal programs that foster innovations and, in turn, by expanding our portfolio of carbon-free, 24/7 renewable energy solutions. AES programs such as APEX (AES Performance Excellence) provide our people with opportunities to generate the next big idea that can expand our businesses, operations, and the services we provide to our customers."],
            ["1","Allgäuer Überlandwerk","Germany","2022","https://auew.de/","AÜW is a medium-sized regional energy supplier based in Kempten in the Allgäu region of Germany. AÜW provides reliable energy supply to around 90,000 customers and possesses a wealth of experience in electric vehicles, virtual power plants, generation plants and energy trading, including dealing with regulations and IT technologies in these areas."],
            ["1","ASA Automation","Germany","2020","https://www.asa-automation.com/","ASA Automation is engineering, building, and installing high-tech automation solutions custom tailored to suit our clients’ specific needs and their products, working from our German facility at Mainhausen, in the vicinity of Frankfurt/Main. For clients in South America, we have founded a subsidiary, ASA Automation SpA, located in Santiago de Chile. ASA’s expertise ranges from the implementation of complex turnkey projects, through the interlinking of machinery, systems, and isolated single-function modules, to retrofitting existing systems. ASA Automation also provides extensive after-sales service for everything we supply. Our conveyor and handling systems are primarily employed in fabrication, assembly, processing, and packaging operations."],
            ["1","Austin Consultants","UK","2021","https://austinconsultants.com/","Austin Consultants offer innovative and flexible client-focused engineering design, development, integration and test solutions that fulfil your business and technical goals. With the rapid advances in electrification technologies in the automotive industry and the accelerated global adoption of Electric Vehicles, Austin Consultants has agreed a contract to provide the Control and Data Acquisition System for Electric Vehicle (EV) powertrain test cells."],
            ["1","Austrian Power Grid","Austria","2020","https://www.apg.at/","Austrian Power Grid (APG) is Austria’s independent transmission system operator and is responsible for and controls Austria’s national transmission grid. Its infrastructure is the lifeline for the country, its population and its businesses. The APG grid spans about 3,400 km and is operated, maintained and constantly adapted to the increasing challenges of society and economy by a team of approximately 500 specialists. APG creates security of supply to ensure that everybody has enough electricity when needed. As one-stop-shop APG is an important service provider in the energy sector. APG’s staff develop suitable market products, master physics and guarantee energy security and efficiency for Austria."],
            ["1","Blockdaemon (AnyBlock Analytics)","USA","2019","https://blockdaemon.com/","At Blockdaemon, we empower businesses to quickly deploy and iterate innovative blockchain applications. We aim to reduce the complexity of working with blockchains through quick and easy configuration, monitoring for high availability and quality of service with enterprise-grade security."],
            ["1","Blok-Z","Turkey","2021","https://www.blok-z.com/","Blok-Z is an energy software startup based in Germany and Turkey. Our mission is to help energy companies unlock new digital energy services that enable consumers to make impactful and individualized energy choices."],
            ["1","bloXmove","Germany","2022","https://bloxmove.com/","bloXmove is a pioneering solutions provider working to create a worldwide decentralized and collaborative urban mobility alliance alongside an efficient green energy reality using blockchain technology. Started by 3 co-founders and supported by a creative and energized team from around the world, bloXmove continues to develop bleeding-edge DLT-powered solutions that bring hyper-efficiency and a spirit of collaboration for mobility providers and a seamless mobility experience for end-users."],
            ["1","Deutsche ErdWärme","Germany","2022","https://www.deutsche-erdwaerme.de/","Deutsche ErdWärme is Germany’s largest private developer of geothermal energy plants. Equipped with several mining permits, Deutsche Erdwärme intends to realise up to twelve geothermal energy projects in the coming years and thus will contribute to a decentralised, reliable supply of carbon-free heat and electricity for the region in the near future."],
            ["1","e-regio","Germany","2022","https://www.e-regio.de/","e-regio is a regionally operating energy utility based in Euskirchen and Kall, North Rhine-Westphalia, Germany. The company is a key driver of the ‘Energiewende’ in the region and supplies residential and commercial customers with renewable electricity from its own PV and wind farms. e-regio also promotes the use of electromobility and carbon-neutral sustainable heat in the region. As a grid operator, digitalizing its distribution grids and making them smarter is another key factor for e-regio."],
            ["1","EDF","France","2018","https://www.edf.fr/","A key player in energy transition, the EDF Group is an integrated electricity company, active in all areas of the business generation, transmission, distribution, energy supply and trading, energy services. A global leader in low-carbon energies, the Group has developed a diversified generation mix based on nuclear power, hydropower, new renewable energies and thermal energy. The Group is involved in supplying energy and services to approximately 38.9 million customers (1), 28.8 million of which are in France. It generated consolidated sales of 71.3 billion in 2019. EDF is listed on the Paris Stock Exchange. Our raison d’être is to build a net zero energy future with electricity and innovative solutions and services, to help save the planet and drive wellbeing and economic development. Wherever our Group operates, we want to invent a new energy model to address the climate crisis: lower-carbon, more efficient, less of an impact on the environment and on people."],
            ["1","Electra Caldense","Spain","2021","https://electracaldenseenergia.com/","ElectraFlex is the world’s first decentralized flexibility platform tailored for the specific needs of a distribution system operator (DSO). The multi-faceted flexibility platform will use Energy Web’s EW-DOS technology stack to assign digital identities to all connected assets and flexibility market participants, allowing them to self-register in energy markets, and offer services to Electra Caldense as well as the Spanish transmission system operator (REE) on behalf of their owners."],
            ["1","Electric Blue Trading","Germany","2018","https://www.electricbluetrading.com/","We support the non-for-profit Energy Web Foundation (EWF) to further develop, validate and maintain the Energy Web Token (EWT) blockchain in order to build the EW-DOS (Energy Web Decentralized Operating System). This blockchain technology eliminates the challenge of double counting energy transactions,and thus the need for a middle man, which dramatically lowers transaction cost and allows small prosumers of energy to directly and effectively exchange energy with each other. Example use cases are solar panels on roofs, electric vehicle charging stations, IoT and corss-grid battery optimisation to name a few."],
            ["1","Elia Group","Belgium","2017","https://www.eliagroup.eu/","Elia Group is an electricity transmission system operator (TSO) ensuring that production and consumption are balanced around the clock, supplying 30 million end users with electricity. With subsidiaries in Belgium (Elia) and northeast Germany (50Hertz), Elia Group develops, maintains, and operates 19,271 km of high-voltage network and is one of Europe's top five TSOs. With a reliability level of 99.99%, we give society a robust power grid, which is important for socio-economic prosperity. We also aspire to be a catalyst for a successful energy transition towards a reliable, sustainable, and affordable energy system. By expanding international high-voltage connections and integrating ever-increasing amounts of renewable energy production, Elia Group promotes both the integration of the European energy market and the decarbonization of our society. The Elia Group is also innovating its operational systems and developing market products so that new technologies and market parties can access our grid, thus making the energy transition happen."],
            ["1","Elocity","Canada","2019","https://elocitytech.com/","Elocity is striving to make the world a better place through innovations in clean energy space. We are building a global infrastructure to make the electric vehicles transition viable, affordable and sustainable by working closely with the utility sector and governments. Headquartered in Canada, we are a team of highly specialized domain experts and problem solvers. As more and more electric vehicles are getting connected to the grid day by day, through our innovations, we are enabling utilities to manage their infrastructure needs and be future ready."],
            ["1","EnerjiSA","Turkey","2021","http://enerjisa.com/","With innovative and differentiated practices in electricity distribution and sales business areas, EnerjiSA provides utility services for the residential, commercial, and industrial sectors in Turkey. We reach 10.1 million customers in 14 provinces with our 3 distribution regions, namely Başkent, Ayedaş and Toroslar, and provide services to more than 21.5 million users."],
            ["1","Engie","Germany","2018","https://engie-energyaccess.com/","ENGIE Energy Access is the leading Pay-As-You-Go (PAYGo) and mini-grids solutions provider in Africa. The company develops innovative, off-grid solar solutions for homes, public services, and businesses, enabling customers and distribution partners access to clean, affordable energy. The PAYGo solar home systems are financed through affordable installments from $0.19 per day, and the mini-grids foster economic development by enabling electrical productive use and triggering business opportunities for entrepreneurs in rural communities. With over 1,700 employees, operations in nine countries across Africa (Benin, Côte d’Ivoire, Kenya, Mozambique, Nigeria, Rwanda, Tanzania, Uganda, and Zambia), almost 1.5 million customers, and more than 7 million lives impacted so far, ENGIE Energy Access aims to remain the leading clean energy company, serving millions of customers across Africa by 2025."],
            ["1","Evolugen (Brookfield Renewables)","Canada","2022","https://evolugen.com/","Evolugen currently owns and operates 61 renewable energy facilities in Canada, including 33 hydroelectric facilities, 4 wind farms, and 24 solar sites, with a total installed capacity of 1,912 MW. As a renewable energy industry leader, Evolugen provides sustainable solutions designed to accelerate the transition to a low-carbon future in Canada. Evolugen is a Brookfield Renewable Partners L.P. company. Brookfield Renewable Partners is one of the world’s largest publicly traded renewable energy."],
            ["1","Energy Web","Switzerland","2017","http://www.energyweb.org/","Energy Web (EW) is a global nonprofit organization accelerating a low-carbon, customer-centric electricity system by unleashing the potential of blockchain and other decentralized technologies. EW focuses on building core infrastructure and shared technology, speeding adoption of commercial solutions, and fostering a community of practice. In 2019 EW launched the Energy Web Chain, the world’s first open-source, enterprise blockchain platform tailored to the energy sector. EW’s technology roadmap has since grown to include the Energy Web Decentralized Operating System (EW-DOS), a “blockchain-plus” suite of decentralized solutions. EW also grew the world’s largest energy blockchain ecosystem comprising utilities, grid operators, renewable energy developers, corporate energy buyers, and others."],
            ["1","FlexiDAO","Germany","2018","https://www.flexidao.com/","FlexiDAO was created to accelerate the transition towards a decarbonised and decentralised energy industry, leveraging blockchain applications. FlexiDAO's mission is to effectively coordinate millions of distributed energy resources into the grid. It's logo - the octopus - represents that vision: Two thirds of their neurons are located in their tentacles, what scientists call a decentralized brain. Utilities need to become an ‘octopus’ too, locating their brain at the edge of the grid. For that purpose, FlexiDAO offers utilities white-label blockchain applications on top of a middleware platform that can access any blockchain infrastructure in an enterprise-grade, secure way."],
            ["1","Fluvius","Belgium","2018","https://www.fluvius.be/","Fluvius System Operator cv is the independent company that is responsible for building, managing and maintaining the distribution grids for electricity and natural gas in all 300 Flemish municipalities, managing the public lighting in all 300 Flemish municipalities, building, managing and maintaining the sewerage system in 85 Flemish municipalities, managing the cable distribution network in 103 Flemish municipalities , building district heating grids, the duties of a social supplier of energy , the promotion of the rational use of energy and water, and supporting Flemish local authorities in their drive towards more energy efficiency and obtaining the climate objectives."],
            ["1","Foton","Turkey","2020","https://fotonenergy.com/","Foton is a Turkish energy innovation company founded in 2019 in Energy Exchange Istanbul’s Innovation Center. Foton is accelerating the energy transition in Turkey by developing a local digital renewable energy procurement marketplace. The Foton team has extensive experience in energy trading and origination. Foton is an Energy Web Member."],
            ["1","Green Running","UK","2019","https://verv.energy/","A UK company from experts in machine learning, creators of Verv, and bringing advanced insights into energy usage, which is pioneering peer-2-peer energy trading in the UK using AI tech"],
            ["1","Inavitas","Australia","2021","https://www.inavitas.com/","inavitas is at the forefront of researching, developing, and delivering smart energy monitoring and management solutions for all scales’ energy systems. inavitas provides real-time monitoring, control and analytical tools for use in both commercial and residential energy systems in terms of consumption and even production. For industry players in renewable energy production and smart grids, inavitas provides workforce management tools, production/distribution optimization tools and state of the art SCADA systems, including the completion of turnkey design, training and installation."],
            ["1","LO3","USA","2018","https://lo3energy.com/","LO3 Energy builds and deploys cloud-based marketplace infrastructure for utilities and retail energy providers across the US, Europe, Japan and Australia. Our product, Pando, helps these suppliers engage customers in new ways amidst more distributed energy resources coming onto the distribution systems. Pando allows businesses and households to buy and sell energy from DERs within their community and allows suppliers to manage these assets using market and price signals. It is a white labeled product that our partners offer to communities in their service territories as a means to acquire, enhance and retain customer relationships. The platform lays foundational infrastructure to manage increasingly granular, complex transactions from the grid edge going forward."],
            ["1","Mercados Electricos","El Salvador","2019","https://www.mercadoselectricos.com.sv/","Mercados Electricos is a leading Salvadoran company in the regional commercialization of electric energy. Our risk management and continuous analysis of the Central American markets, allows us to offer the best optimization of the availability and/or requirements of any agent of the regional electric sector, through the tools provided by the Regional Electric Market."],
            ["1","Nethermind","UK","2020","https://nethermind.io/","Founded in 2017 by a small team of world-class technologists, Nethermind builds Ethereum solutions for developers and enterprises. Boosted by a grant from the Ethereum Foundation in August 2018, our team has worked tirelessly to deliver the fastest Ethereum client in the market. In addition to the client, the Nethermind team has built a peer-to-peer Data Marketplace, run multiple free Advanced EVM workshops to educate developers, and been actively involved with Ethereum Core development. Nethermind is also a maintainer of the Baseline Protocol, and is working to deliver Ethereum 2.0."],
            ["1","OLI Systems","Germany","2018","https://www.my-oli.com/","OLI allows consumers and decentralized producers to actively participate in the energy transition. Using blockchain-supported software and hardware components, they form a distributed network in which you can share electricity in the neighborhood, in the district, in the region and throughout Germany."],
            ["1","PTT Group","Thailand","2017","https://www.pttplc.com/","PTT Public Company Limited is a Thai state-owned energy conglomerate. It is the largest business conglomerate in Thailand with 280+ subsidiaries in 25+ countries, is the only Thai company in Fortune global 500, and has annual revenues exceeding US$55 billion. PTT owns 100% of gas pipeline and gas separation plants in Thailand. PTT is prioritizing the UN’s Sustainable Development Goal #7 (Affordable and Clean Energy) in its strategy as it expands investments in renewable energy and low-carbon solutions."],
            ["1","SB Energy","Japan","2017","https://www.sbenergy.co.jp/","SB Energy sets its core business in three categories: the Watts Business that generates power using natural energy; the Bits Business that combines renewable energy with AI and IoT to build energy platforms;and the Mobility Business that combines renewable energy with battery cells of electric vehicles (EVs) etc. to develop services. Based on these three categories, we expand our business domains and help spread the use of renewable energy. Through the Golden Triangle of the Bits, Watts, and Mobility Businesses, we build energy platforms in Japan and the world. We also build new business models to cope with massive industrial structure changes, being prompted as renewable energy is now redefining industries."],
            ["1","Scytale Ventures","Austria","2018","https://scytale.ventures/","We are a team of investment management experts, blockchain technology experts, and entrepreneurs who share a vision about the impact of blockchain technology and accompanied Web 3 technologies."],
            ["1","South Pole","Switzerland","2022","https://www.southpole.com/","South Pole develops and implements comprehensive emission reduction projects and strategies that turn climate action into long-term business opportunities for companies, governments and organizations around the world. We help realise deep decarbonisation pathways across industries, based on a thorough understanding of climate risks and opportunities in specific sectors, as well as the highest emission reduction standards."],
            ["1","SP Group","Singapore","2017","https://www.spgroup.com.sg/","SP Group (SP) is a leading energy utilities company in Asia Pacific. One of Singapore’s largest corporations, SP recorded revenues of S$4 billion and assets of S$20 billion in FY19/20. SP owns and operates electricity and gas transmission and distribution businesses in Singapore and Australia. It also owns and operates the world’s largest underground district cooling network in Singapore, and is setting up district cooling operations in China. More than 1.6 million industrial, commercial and residential customers in Singapore benefit from SP’s world-class transmission, distribution and market support services. The SP networks in Singapore are amongst the most reliable and cost-effective worldwide."],
            ["1","Stadtwerke Klagenfurt","Austria","2022","https://www.stw.at/","STW is a multifaceted company that supplies the residents and businesses of Klagenfurt am Wörthersee, capital of Carinthia, with energy (electricity, gas, district heating, photovoltaics), water, telecommunications, public transport, and leisure facilities. As an energy network operator and energy supplier, Stadtwerke Klagenfurt is an important driver in the energy transition."],
            ["1","Stedin","Netherlands","2017","https://www.stedin.net/","Stedin Group, ensure that our customers have access to energy via our grids throughout the year. We are proud that our grids are among the most reliable grids in the world. As energy has become indispensable in the world we live in. We take it for granted that energy is always available. We use energy for everything, at every moment, and we are using more and more of it. At home, on the road and at work."],
            ["1","Tenaska Power Services","USA","2020","https://www.tenaska.com/","Over 35 years, Tenaska has grown to be a national leader adept in natural gas marketing, power marketing and energy management, development and acquisition of generation assets, operation of power plants and much more."],
            ["1","Terna Energy","Greece","2022","https://www.terna-energy.com/","With a strong portfolio of projects in Greece and abroad, Terna Energy is the largest investor in the renewable energy sector in Greece playing a leading role in clean energy production while carrying out innovative projects for the environment, which contribute to sustainable development. Terna Energy forms part of the energy Group GEK TERNA."],
            ["1","TWL","Germany","2021","https://www.twl.de/","Technische Werke Ludwigshafen AG (hereinafter referred to as TWL) is a municipal utility company that has been responsible for the reliable supply of energy and water to the city of Ludwigshafen for more than 100 years now. In relation to the energy transition, TWL is transforming its core business towards a sustainable management and corporate behaviour step by step."],
            ["1","UTE","Uruguay","2020","https://www.ute.com.uy/","The National Administration of Power Plants and Electrical Transmissions, better known as UTE, is Uruguay's government-owned power company. It was established in 1912, following approval of Law 4273 establishing it as a monopoly."],
            ["1","Vodafone","UK","2020","https://vodafone.com/","Vodafone DAB solves the problem of most existing connected devices and systems tending to operate in isolation. Vodafone DAB platform provides a single point for trusted vehicles, or any other device, to interact across multiple car parks or systems."],
            ["1","Wirepas","Finland","2018","https://wirepas.com/","Wirepas is an international technology company focused on IoT connectivity software development. We offer our clients a development environment, which ensures the flow of data between devices and backend reliably. All of this is possible thanks to our extremely experienced, ambitious and passionate team. Wirepas Mesh is a wireless connectivity technology for massive IoT. Wirepas Mesh running in the devices enables a scalable, reliable, and cost-efficient IoT solution. The network provides one horizontal connectivity layer for all IoT use cases: collect data from your sensors to an IoT application in the cloud, control remotely located devices, communicate device-to-device in the network with or without cloud and track the location of moving assets. All the networking intelligence is included in the Wirepas Mesh software to form a resilient large-scale wireless mesh network."],
            ["1","Zytech","Spain","2020","http://zytechsolar.com/","Zytech Solar is a leading Solar Panels Manufacturer since 2006. It belongs to Zytech Group, Headquartered in Spain, we have our own production plants in India, China, final assembly in Spain and subsidiaries in 8 countries."],
            ["0","Vestas","Denmark","2020","https://www.vestas.com/","Vestas is the energy industry’s global partner on sustainable energy solutions. We design, manufacture, install, and service wind turbines across the globe, and with more than 108 GW of wind turbines in 80 countries, we have installed more wind power than anyone else. Through our industry-leading smart data capabilities and unparalleled 90 GW of wind turbines under service, we use data to interpret, forecast, and exploit wind resources and deliver best-in-class wind power solutions. Together with our customers, Vestas’ more than 25,000 employees are bringing the world sustainable energy solutions to power a bright future."],
            ["0","Community Electricity","USA","2020","https://www.communityelectricity.io/","We are an innovative Community Electricity Developer, a 100% local and clean electricity service provider. We assess, aggregate, finance and develop existing and new distributed clean electricity assets across communities. Once connected, these flexible assets become Virtual Power Plants where members can take advantage of the market volatility by selling their electricity at tactical prices. Community Electricity is committed to decarbonize, digitize and electrify our neighborhoods while transforming them into resilient urban micro-utilities."]
        ];

        foreach($validators as $validator_seed) {
            $validator = new Validator;
            $validator->active = $validator_seed[0];
            $validator->name = $validator_seed[1];
            $validator->location = $validator_seed[2];
            $validator->since = $validator_seed[3];
            $validator->url = $validator_seed[4];
            $validator->description = $validator_seed[5];
            $validator->save();
            //dump($validator);
        }

    }
}
